erDiagram
    "TMP.AppointmentRequest" {
        bigint AppointmentRequestUid
        datetime RequestedAppointmentDateTime
        nvarchar CustomerDetails
        nvarchar VehicleDetails
        nvarchar PreferredContactMethod
        nvarchar GroupName
        nvarchar ReasonForVisit
        nvarchar ScheduleWaitingOption
        nvarchar ScheduleServiceCategories
        tinyint Status
        datetime DateAcknowledgedUTC
        datetime SubmitDateTimeUTC
        nvarchar CustomerComment
        nvarchar ShopComment
        int CustomerId
        int VehicleId
        timestamp RowVersion
        tinyint Type
        nvarchar FleetDetails
        nvarchar SupplementalProperties
    }
    "TMP.CacheOnlineCatalog" {
        int Id
        datetime Expiration
        nvarchar Item
    }
    "TMP.CommissionLineItems" {
        int RepairOrderId
        int Invoice
        datetime DatePosted
        int WriterId
        nvarchar WriterName
        int LineItemId
        int CustId
        nvarchar CustomerName
        nvarchar LineItemDescription
        money Sale
        money Cost
        bit NoCommission
        bit FixedCommission
        int CategoryId
        money HoursCharged
        int LineItemType
        bit TreatAsPart
        int VehicleId
        nvarchar YMM
        int WriterCommTypeLabor
        money WriterCommLabor
        int WriterCommTypeParts
        money WriterCommParts
        int WriterCommTypeSublet
        money WriterCommSublet
        bit MultipleTechs
        bit WriterDeleted
        int OrderRevisionId
    }
    "TMP.CommissionLineItemTechs" {
        int RepairOrderId
        int Invoice
        datetime DatePosted
        int WriterId
        nvarchar WriterName
        int LineItemId
        int CustomerId
        nvarchar CustomerName
        nvarchar LineItemDescription
        money Sale
        money Cost
        bit NoCommission
        bit FixedCommission
        int CategoryId
        money HoursCharged
        int LineItemType
        bit TreatAsPart
        int VehicleId
        nvarchar YMM
        int WriterCommTypeLabor
        money WriterCommLabor
        int WriterCommTypeParts
        money WriterCommParts
        int WriterCommTypeSublet
        money WriterCommSublet
        bit MultipleTechs
        int EmployeeId
        money HoursActual
        money LaborHours
        money FixedCommValue
        nvarchar TechName
        money CommissionParts
        money CommissionLabor
        money CommissionTypeParts
        money CommissionTypeLabor
        money HourlyRate
        bit EmployeeDeleted
        bit WriterDeleted
    }
    "TMP.CommissionRepairOrders" {
        int RepairOrderId
        datetime DatePosted
        int Invoice
        int CustId
        nvarchar CustomerName
        int VehicleId
        nvarchar YMM
        int WriterId
        nvarchar WriterName
        int WriterCommTypeLabor
        money WriterCommLabor
        int WriterCommTypeParts
        money WriterCommParts
        int WriterCommTypeSublet
        money WriterCommSublet
        bit WriterDeleted
        int OrderRevisionId
    }
    "TMP.EmployeeLineCommissions" {
        int EmployeeId
        int EmployeeType
        int LineItemType
        int LineItemId
        money CommissionRate
        int CommissionBasis
        money LaborHours
        money Salary
        money CommissionPaid
        money Sale
        nvarchar LineItemDescription
        int Invoice
        datetime DatePosted
        nvarchar TechName
        int RepairOrderId
        int CategoryId
        nvarchar YMM
        int CommissionTypeParts
        int CommissionTypeLabor
        int CommissionTypeSublet
        money CommissionParts
        money CommissionLabor
        money CommissionSublet
        bit EmployeeDeleted
        nvarchar CustomerName
        money HoursActual
        money HoursCharged
        bit MultipleTechs
        bit TreatAsPart
        bit NoCommission
        bit HasCommission
    }
    "TMP.LineItemCosts" {
        int LineItemId
        int LineItemType
        money Salary
        money Commission
        money EmployeeCosts
        money MaterialCosts
        money TotalCosts
        money Sale
        money Profit
        int WriterId
    }
    "TMP.LoggedPhoneNumbers" {
        int PhoneId
        int CustId
        nvarchar PhoneNum
        nvarchar Ext
        varchar Description
    }
    "TMP.MessageQueueSetting" {
        int Id
        date LastCleaned
    }
    "TMP.MROOOLIST" {
        datetime LastAccess
        int RepairOrderId
    }
    "TMP.ReservePONumber" {
        int Id
        int ReservePONumberGroupId
    }
    "TMP.ReservePONumberGroup" {
        int Id
        bit Freed
        datetime Created
    }
    "TMP.RevisionShare" {
        int Id
        int OrderRevisionId
        bigint DataFileId
        bigint ShareFileId
        nvarchar ShareUrl
        nvarchar Filename
        datetime Date
    }
    "TMP.WebPortalUserSession" {
        bigint Id
        int UserId
        uniqueidentifier SessionId
        datetime2 IssuedAtUTC
        datetime2 ExpiresUTC
        datetime2 CreatedUTC
    }
    "TMP.ReservePONumberGroup" ||--o{ "TMP.ReservePONumber" : "FK_ReservePONumberGroup_ReservePONumber"
    %% Cross-schema: "SM.OrderRevision" ||--o{ "TMP.RevisionShare" : "FK_RevisionShare_OrderRevision"