erDiagram
    "DPR.CatalogsDataExchange" {
        int ExchangeId
        nvarchar CatalogName
        int RepairOrderId
        int PurchaseOrderId
        nvarchar VendorInfo
        nvarchar VehicleInfo
        nvarchar DataTransfered
        nvarchar DataReceived
        datetime DateRecorded
        int ActionType
        int RecordVersion
        datetime2 LastChangeDate
    }