erDiagram
    "QBI.PackageMapping" {
        int PackageMappingId
        int PackageID
        int OriginalId
        nvarchar OriginatingTableName
    }
    "QBI.PartKitMapping" {
        int PartKitMappingId
        int PartKitId
        int OriginalId
        nvarchar OriginatingTableName
    }
    "QBI.PaymentMapping" {
        int PaymentMappingId
        int PaymentId
        int OriginalId
        nvarchar OriginatingTableName
    }